add rock 5c profile
radxa-pkg/radxa-profiles pull request #16
Opened 2024-02-06 06:41 UTC by vamrs-feng

2024-02-06 06:44 UTC, RadxaYuntian requested changes

2024-02-06 06:44 UTC, RadxaYuntian commented on debian/control
> +         aic8800-dkms,
看看别的aic8800的产品是怎么定义的，都有`rsetup-config-hciattach-ttys1`
5C是用ttyS1作为蓝牙串口么?

2024-02-06 06:47 UTC, vamrs-feng commented on debian/control
> +         aic8800-dkms,
5C USB接口共用 WIFI/BT

2024-02-06 06:48 UTC, RadxaYuntian commented on debian/control
> +         aic8800-dkms,
我们现在aic8800-dkms只支持sdio wifi

2024-02-06 06:48 UTC, vamrs-feng commented on debian/control
> +         aic8800-dkms,
这个 R8125的包是不是可以不用

2024-02-06 06:49 UTC, vamrs-feng commented on debian/control
> +         aic8800-dkms,
对，后面我需要提交那个USB 的支持

2024-02-06 06:52 UTC, RadxaYuntian commented on debian/control
> +         aic8800-dkms,
那等usb支持弄好了再合并这个pr
8125如果你产品没有用到可以不要

2024-02-06 06:52 UTC, vamrs-feng commented on debian/control
> +         aic8800-dkms,
好的

2024-02-21 10:46 UTC, RadxaYuntian approved these changes

2024-02-21 10:46 UTC, merged