feat: add medge-rk3528a-io
radxa-pkg/radxa-profiles pull request #25
Opened 2024-08-01 09:58 UTC by lsj123lsjlsj

feat: add medge-rk3528a-io

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-08-01 11:27 UTC, RadxaYuntian requested changes

2024-08-01 11:27 UTC, RadxaYuntian commented on debian/control
> +Package: task-medge-rk3528a-io
类似bsp需要修改产品id

2024-08-01 11:27 UTC, RadxaYuntian commented on debian/control
> +Description: Metapackages for mEdge series
```suggestion
Description: Metapackages for mEdge RK3528A IO
```
这个明显不会跟别的mEdge产品共用

2024-08-06 06:26 UTC, RadxaYuntian requested changes

2024-08-06 06:26 UTC, RadxaYuntian commented on debian/control
> +Description: Metapackages for mEdge RK3528A IO
```suggestion
Description: Metapackages for Radxa mEdge RK3528A IO
```

2024-08-06 07:52 UTC, RadxaYuntian requested changes

2024-08-06 07:52 UTC, RadxaYuntian commented on debian/control
> +Description: Metapackages for mEdge RK3528A IO
你这明明都没改怎么就点reslove conversation

2024-08-06 07:53 UTC, RadxaYuntian approved these changes

2024-08-06 07:53 UTC, lsj123lsjlsj commented on debian/control
> +Description: Metapackages for mEdge RK3528A IO
我以为可以先点后改，明白了

2024-08-06 08:02 UTC, merged